windows_10 = [
    "                                ..,",
    "                    ....,,:;+ccllll",
    "      ...,,+:;  cllllllllllllllllll",
    ",cclllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "                                   ",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "llllllllllllll  lllllllllllllllllll",
    "`'ccllllllllll  lllllllllllllllllll",
    "       `' \\*::  :ccllllllllllllllll",
    "                       ````''*::cll",
    "                                 ``"
]

windows_11 = [
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################",
    "                                   ",
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################",
    "################   ################"
]
