name: Type & Lint check PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install_dev

      - name: Run Ruff
        run: make lint

  pyright:
    name: Pyright
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install_dev

      - name: Run Pyright
        run: make type
